---
- name: Gestion de Apache2 en CentOS7
  hosts: all
  become: yes
  tasks:
    - name: Menu de seleccion
      block:
        - name: Mostrar opciones
          pause:
            prompt: "Selecciona una opcion:\n1. Obtener estado de Apache\n2. Detener Apache\n3. Iniciar Apache"
          register: menu_selection
          until: menu_selection.user_input in ['1', '2', '3']
          retries: 3

        - name: Obtener estado de Apache
          command: systemctl is-active httpd
          register: apache_status

        - name: Mostrar resultado
          debug:
            var: apache_status.stdout
          when: menu_selection.user_input == '1'

        - name: Detener Apache
          service:
            name: httpd
            state: stopped
          when: menu_selection.user_input == '2'

        - name: Iniciar Apache
          service:
            name: httpd
            state: started
          when: menu_selection.user_input == '3'